default:
  image:
    name: ${CPU_IMAGE}
    pull_policy: always
  tags:
    - ${RUNNER_TAG}

variables:
  GIT_STRATEGY: clone
  RUNNER_TAG: "pss-dokimi-docker"  # Default runner for all jobs
  LINT_RUNNER_TAG: "pss-dokimi-docker"  # Runner for lint jobs
  CI_CPU_IMAGE_TAG: "ci-ubuntu22.04"
  CI_REGISTRY_IMAGE: "registry.gitlab.com/ska-telescope/pss/ska-pss-astrotypes"
  CPU_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_CPU_IMAGE_TAG}

stages:
  - lint
  - build
  - test
  - publish-docs

.common:
  rules:
      # Execute pipeline automatically if commit is made to main
      # (this should only happen when code is merged to main)
    - if: $CI_COMMIT_BRANCH == "main"

      # Create but do not execute pipeline for feature branches on commit,
      # or if created via the gitlab GUI
    - if: ($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "api")
      when: manual
      allow_failure: false

      # Execute pipeline if triggered by a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"

      # Execute pipeline automatically if triggered by a MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    
      # Execute pipeline automatically if triggered via the web GUI
    - if: $CI_PIPELINE_SOURCE == "web"

lint:
  stage: lint
  rules:
      # Execute job automatically if commit is made to main
      # (this should only happen when code is merged to main)
    - if: $CI_COMMIT_BRANCH == "main"
      allow_failure: true

      # Execute job if triggered by a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      allow_failure: true

      # Execute job automatically if triggered by a MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      allow_failure: true
  tags:
    - ${LINT_RUNNER_TAG}
  script:
    - cmake --version
    - clang-tidy --version
    - mkdir build && cd build
    - 'cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=release ..'
    - 'run-clang-tidy -checks=''cppcoreguidelines-*,performance-*,readibility-*,modernize-*,misc-*,clang-analyzer-*,google-*,
      -cppcoreguidelines-pro-type-reinterpret-cast,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-modernize-use-nodiscard''
      -quiet 2>&1 | tee clang-tidy.log'
  artifacts:
    name: "$CI_COMMIT_REF_NAME-lint"
    when: on_failure
    paths:
      - build/clang-tidy.log
    expire_in: 1 d

.builds:
  stage: build
  extends: .common
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=../install $CMAKE_FLAGS ..
    - make -j
    - make -j install
  artifacts:
    name: "$CI_COMMIT_REF_NAME-build"
    paths:
      - build/*
    expire_in: 1 d

.tests:
  stage: test
  extends: .common
  script:
    - cd build && mkdir reports
    - ctest --output-on-failure --force-new-ctest-process --output-junit reports/test-results-$SPIN.xml
  artifacts:
    paths:
      - build/
    reports:
      junit: build/reports/test-results-$SPIN.xml

build-release:
  extends: .builds
  variables:
    CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=release"

build-debug:
  extends: .builds
  variables:
    CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=debug"

test-release:
  extends: .tests
  needs:
    - build-release
  variables:
    SPIN: release

test-debug:
  extends: .tests
  needs:
    - build-debug
  variables:
    SPIN: debug

doc-build:
  stage: build
  extends: .common
  script:
    - mkdir build-docs && cd build-docs
    - cmake -DCMAKE_BUILD_TYPE=documentation ..
    - make doc
  artifacts:
    paths:
      - build-docs/
  only:
    - main

pages:
  stage: publish-docs
  image: alpine
  script:
    - mv build-docs/doc/html/ public/
  needs:
    - doc-build
  artifacts:
    paths:
      - public/
  only:
    - main