variables:
    GIT_STRATEGY: clone
    CUDA_PATH: -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-11.6/
stages:
  - set-up
  - build
  - lint
  - test
  - publish-docs

.common:
  rules:
      # Execute pipeline automatically if commit is made to dev or main
      # (this should only happen when code is merged to dev or main)
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"

      # Create but do not execute pipeline for feature branches on commit,
      # or if created via the gitlab GUI
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "api"
      when: manual
      allow_failure: false

      # Execute pipeline if triggered by a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"

      # Execute pipeline automatically if triggered by a MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

# This job sets up a symbolic link to from the root repository to build/ska-pss-astrotypes/source.
# astrotypes/build
# astrotypes/install
# astrotypes/source
# We put the above structure inside an additional 'build' directory to comply with SKAO CICD Pipeline conventions.
set-up:
  stage: set-up
  extends: .common
  script:
    - mkdir build && cd build
    - mkdir astrotypes && cd astrotypes
    - cd ../../
    - ln -s $CI_PROJECT_DIR/ build/astrotypes/source
  tags:
    - ubuntu-18.04
  artifacts:
    name: "$CI_COMMIT_REF_NAME-cheetah"
    paths:
      - build/astrotypes/source/*
    expire_in: 1 d

.builds:
  needs: set-up
  stage: build
  extends: .common
  tags:
    - ubuntu-18.04
  script:
    - cd build
    - mkdir astrotypes && cd astrotypes
    - git clone https://gitlab.com/ska-telescope/pss/ska-pss-astrotypes.git source
    - mkdir build install
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=../install $CMAKE_FLAGS ../source
    - make -j
    - make install
  artifacts:
    name: "$CI_COMMIT_REF_NAME-astrotypes-install"
    paths:
      - build/astrotypes/install/*
    expire_in: 1 d

lint:
  stage: lint
  needs:
    - set-up
    - build-release
  image: ubuntu:20.04
  rules:
      # Execute job automatically if commit is made to dev or main
      # (this should only happen when code is merged to dev or main)
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"
      allow_failure: true

      # Execute job if triggered by a schedule
    - if: $CI_PIPELINE_SOURCE == "schedule"
      allow_failure: true

      # Execute job automatically if triggered by a MR
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      allow_failure: true
  tags:
    - k8srunner
  script:
    - apt-get -y update
    - apt install -y cmake
    - cmake --version
    - apt install -y python3 gcc g++ libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libfftw3-dev git
    - apt install -y clang-tidy
    - clang-tidy --version
    - cd build/astrotypes
    - mkdir build && cd build
    - 'cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      -DCMAKE_BUILD_TYPE=release -DENABLE_CUDA=false ../source'
    - 'run-clang-tidy -checks=''cppcoreguidelines-*,performance-*,readibility-*,modernize-*,misc-*,clang-analyzer-*,google-*,
      -cppcoreguidelines-pro-type-reinterpret-cast,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-modernize-use-nodiscard''
      -quiet 2>&1 | tee clang-tidy.log ../source/astrotypes'
  artifacts:
    name: "$CI_COMMIT_REF_NAME-lint"
    when: on_failure
    paths:
      - build/astrotypes/build/clang-tidy.log
    expire_in: 1 d
  
.tests:
  needs:
    - set-up
  stage: test
  extends: .common
  tags:
    - ubuntu-18.04
  script:
    - cd build
    - make test

build-release:
  extends: .builds
  variables:
    CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=release -DENABLE_CUDA=false"

build-debug:
  extends: .builds
  variables:
    CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=debug -DENABLE_CUDA=false"

build-cuda-release:
  extends: .builds
  variables:
    CMAKE_FLAGS: "$CUDA_PATH -DCMAKE_BUILD_TYPE=release -DENABLE_CUDA=true"

build-cuda-debug:
  extends: .builds
  variables:
    CMAKE_FLAGS: "$CUDA_PATH -DCMAKE_BUILD_TYPE=debug -DENABLE_CUDA=true"

build-nasm-release:
  extends: .builds
  variables:
    CMAKE_FLAGS: "$CUDA_PATH -DCMAKE_BUILD_TYPE=release -DENABLE_NASM=true"

build-nasm-debug:
  extends: .builds
  variables:
    CMAKE_FLAGS: "$CUDA_PATH -DCMAKE_BUILD_TYPE=debug -DENABLE_NASM=true"

build-cuda-nasm-release:
  extends: .builds
  variables:
    CMAKE_FLAGS: "$CUDA_PATH -DCMAKE_BUILD_TYPE=release -DENABLE_CUDA=true -DENABLE_NASM=true"

build-cuda-nasm-debug:
  extends: .builds
  variables:
    CMAKE_FLAGS: "$CUDA_PATH -DCMAKE_BUILD_TYPE=debug -DENABLE_CUDA=true -DENABLE_NASM=true"

test-release:
  extends: .tests
  needs:
    - build-release

test-debug:
  extends: .tests
  needs:
    - build-debug

test-cuda-release:
  extends: .tests
  needs:
    - build-cuda-release

test-cuda-debug:
  extends: .tests
  needs:
    - build-cuda-debug

test-nasm-release:
  extends: .tests
  needs:
    - build-nasm-release

test-nasm-debug:
  extends: .tests
  needs:
    - build-nasm-debug

test-cuda-nasm-release:
  extends: .tests
  needs:
    - build-cuda-nasm-release

test-cuda-nasm-debug:
  extends: .tests
  needs:
    - build-cuda-nasm-debug


doc-build:
  stage: build
  image: alpine
  script:
    - apk update && apk add git build-base cmake3 doxygen graphviz ttf-freefont
    - git clone https://gitlab.com/ska-telescope/pss/ska-pss-astrotypes.git
    - mkdir build-docs
    - cd build-docs
    - cmake3 -DCMAKE_BUILD_TYPE=documentation -DPANDA_SOURCE_DIR=../panda/ -DASTROTYPES_SOURCE_DIR=../astrotypes ../
    - make doc
  artifacts:
    paths:
      - build-docs/
  only:
    - main

pages:
  stage: publish-docs
  image: alpine
  script:
    - mv build-docs/doc/html/ public/
  needs:
    - doc-build
  artifacts:
    paths:
      - public/
  only:
    - main
